# Generated by Django 5.0.6 on 2025-10-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_direccion_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grupo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='user.grupo'),
        ),
        migrations.AddField(
            model_name='taller',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
